### PR TITLE
fix: correctly separating the vendor folder when running `sls deploy function`

### LINKED ISSUE #1186: Separate Vendor: Failed opening required file
**Description:**

I have a large vendor folder (~100MB production optimized) and have `bref.separateVendor = true`.
I then sometimes get the `Failed opening file` error which it encounters while trying to get the symfony polyfill file. 

```
Fatal error: require(): Failed opening required '/tmp/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/opt/bref/lib/php') in /tmp/vendor/composer/autoload_real.php on line 55
```

Sometimes I get this error, and sometimes not. But when I do, subsequent invocations error out for a span of 5 mins to as long as 2 hours.

### PR DESCRIPTION
**Pull request by afu-dev**
Fixes #1186 

- Changed the hook event for the first step (`addCustomIamRoleForVendorArchiveDownload`). The event `initialize` is common to both `sls deploy` AND `sls deploy function`.
- Added `before:deploy:function:initialize` and `after:deploy:function:initialize` for, respectively, `createVendorZip` and `uploadVendorZip` steps. Only executed when running the `sls deploy function` command.
- Added a few logs just to be safe when checking for the fix.

<details>
  <summary>Logs when running both commands:</summary>

```console
➜  bref-debug git:(main) ✗ sls deploy --verbose
To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^3.21.0")


Deploying bref-debug to stage debug (eu-west-1)

Bref: Adding custom IAM role for vendor archive
Packaging
Bref: Creating vendor zip file
Bref: Packaging the Composer vendor directory in .serverless/vendor.zip
Bref: Created vendor.zip with 887792 total bytes.
Bref: Setting environment variables
Excluding development dependencies for service package
Retrieving CloudFormation stack
Bref: Uploading vendor zip file...
Bref: Checking vendor file on bucket...
Bref: Vendor file not found. Uploading...
Bref: Vendor separation done
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service bref-debug.zip file to S3 (14.41 kB)
Updating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Executing created change set
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - bref-debug-debug
  UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
  UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - HelloLambdaFunction
  UPDATE_COMPLETE - AWS::Lambda::Function - HelloLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloLambdaVersionXztGfLb4JuD0oEmh6yS094sN3regPbnaLPJxZ26VOSE
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloLambdaVersionXztGfLb4JuD0oEmh6yS094sN3regPbnaLPJxZ26VOSE
  CREATE_COMPLETE - AWS::Lambda::Version - HelloLambdaVersionXztGfLb4JuD0oEmh6yS094sN3regPbnaLPJxZ26VOSE
  UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - bref-debug-debug
  DELETE_SKIPPED - AWS::Lambda::Version - HelloLambdaVersionKbQ2C72diKsprKlLbdj5ZKK8fo0Hkg89PYCkrIc4jvw
  UPDATE_COMPLETE - AWS::CloudFormation::Stack - bref-debug-debug
Retrieving CloudFormation stack
Removing old service artifacts from S3

✔ Service deployed to stack bref-debug-debug (78s)

functions:
  hello: bref-debug-debug-hello (14 kB)

Stack Outputs:
  HelloLambdaFunctionQualifiedArn: arn:aws:lambda:eu-west-1:207493619263:function:bref-debug-debug-hello:23
  ServerlessDeploymentBucketName: bref-debug-debug-serverlessdeploymentbucket-rrqp56wlqcf4
➜  bref-debug git:(main) ✗ aws lambda get-function-configuration --function-name bref-debug-debug-hello --region eu-west-1 --profile perso-root | jq .Environment
{
  "Variables": {
    "BREF_DOWNLOAD_VENDOR": "s3://bref-debug-debug-serverlessdeploymentbucket-rrqp56wlqcf4/serverless/vendors/d94aa0f4ed9d2e91bc4fd30199a1faed.zip"
  }
}
➜  bref-debug git:(main) ✗ sls deploy function -f hello --verbose
To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^3.21.0")


Deploying function hello to stage debug (eu-west-1)

Bref: Adding custom IAM role for vendor archive
Validating
Bref: Creating vendor zip file
Bref: Packaging the Composer vendor directory in .serverless/vendor.zip
Bref: Created vendor.zip with 887792 total bytes.
Bref: Setting environment variables
Bref: Uploading vendor zip file...
Bref: Checking vendor file on bucket...
Bref: Vendor file already exists on bucket. Not uploading again.
Bref: Vendor separation done
Retrieving function info
Excluding development dependencies for function "hello"
Packaging

Code did not change. Function deployment skipped. (1s)
Configuration did not change. Configuration update skipped. (1s)
➜  bref-debug git:(main) ✗ aws lambda get-function-configuration --function-name bref-debug-debug-hello --region eu-west-1 --profile perso-root | jq .Environment
{
  "Variables": {
    "BREF_DOWNLOAD_VENDOR": "s3://bref-debug-debug-serverlessdeploymentbucket-rrqp56wlqcf4/serverless/vendors/d94aa0f4ed9d2e91bc4fd30199a1faed.zip"
  }
}

(...)
# Adding a new package
(...)

➜  bref-debug git:(main) ✗ sls deploy function --verbose -f hello 
To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^3.21.0")


Deploying function hello to stage debug (eu-west-1)

Bref: Adding custom IAM role for vendor archive
Validating
Bref: Creating vendor zip file
Bref: Packaging the Composer vendor directory in .serverless/vendor.zip
Bref: Created vendor.zip with 1576500 total bytes.
Bref: Setting environment variables
Bref: Uploading vendor zip file...
Bref: Checking vendor file on bucket...
Bref: Vendor file not found. Uploading...
Bref: Vendor separation done
Retrieving function info
Excluding development dependencies for function "hello"
Packaging
Uploading (17 kB)
Deploying

✔ Function code deployed (19s)
Configuration did not change. Configuration update skipped. (19s)
Retrying ensure function state for function: hello.
➜  bref-debug git:(main) ✗ aws lambda get-function-configuration --function-name bref-debug-debug-hello --region eu-west-1 --profile perso-root | jq .Environment
{
  "Variables": {
    "BREF_DOWNLOAD_VENDOR": "s3://bref-debug-debug-serverlessdeploymentbucket-rrqp56wlqcf4/serverless/vendors/d94aa0f4ed9d2e91bc4fd30199a1faed.zip"
  }
}
```
</details>

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -76,9 +76,15 @@ class ServerlessPlugin {
         }
 
         this.hooks = {
-            'before:package:setupProviderConfiguration': this.addCustomIamRoleForVendorArchiveDownload.bind(this),
+            'initialize': this.addCustomIamRoleForVendorArchiveDownload.bind(this),
```
Comment (t-richard) [inline index.js:79]: Isn't there a "package" event common to both ?

As far as I can tell, `initialize` is common to all commands so this would be executed for all commands (even unrelated ones like logs, invoke, etc).

**Review by t-richard — COMMENTED** [review]
Thanks for starting this @afu-dev !

A small comment

File: index.js (hunk 1 above)
Comment (mnapoli) [reply index.js:79]: Very good point indeed.

That being said, this only adds an IAM role, so it should be fairly fast. And it ensures all commands have the same IAM role/config, so it might actually be a win? WDYT?

Comment (afu-dev) [reply index.js:79]: Indeed @t-richard 🙂 

I tried to log every fired events in the issue: https://github.com/brefphp/bref/issues/1186#issuecomment-1212816753 (I can't be sure I got everything)

By the way, I never worked on a Serverless plugin, it's new territory for me 😅 

But I agree on the fact that only the necessary commands should setup the IAM permissions, even if it's a quick and small step.

**Comment by mnapoli** [comment]
Thank you @afu-dev!
