### PR TITLE
#409 Add a `bref local` command to invoke functions locally

### LINKED ISSUE #409: Serverless invoke local error "Runtime.ExitError"
Edit: **please try the workaround here: https://github.com/brefphp/bref/issues/409#issuecomment-581425967**

---

Hello,

i followed your new documentation under https://bref.sh/docs/local-development.html and get following error if try to run 
"serverless invoke local --docker -f myFunction"

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Building Docker image...
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72	Duration: 0.00 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 6 MB	
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"
}


/usr/lib/node_modules/serverless/lib/classes/Error.js:94
    throw new Error(inspect(e));
          ^
Error: 1
    at process.module.exports.logError.e (/usr/lib/node_modules/serverless/lib/classes/Error.js:94:11)
    at process.emit (events.js:198:13)
    at process.emit (/usr/lib/node_modules/serverless/node_modules/source-map-support/source-map-support.js:465:21)
    at /usr/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:199:33
    at activeFireEvent (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:242:44)
    at fireRejectionEvent (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:632:14)
    at Promise._notifyUnhandledRejection (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:65:9)
    at Timeout._onTimeout (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:44:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

Any idea whats wrong?

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #409. 

This is an attempt at fixing #409 to simplify running functions locally.

**This is not meant to run HTTP applications**, this is meant to run Lambda functions locally.

**Note: this is planned for v1.0.**

## The problem

Here is a PHP function for Lambda:

```php
<?php
return function ($event) {
    echo 'This is a log line' . PHP_EOL;

    return 'Hello ' . ($event['name'] ?? 'world');
};
```

Here is how it is configured in `serverless.yml`:

```php
functions:
    hello:
        handler: my-hello-function.php
        layers:
            - ${bref:layer.php-74}
```

Here is how we can currently run this function locally:

- `serverless invoke local -f hello`
  - 👍 Runs in Docker (mirrors the prod environment)
  - 👍 `serverless` forwards the local AWS credentials, region and AWS profile automatically
  - 🔴 Downloads the layers (once) & builds a local Docker image everytime : this is very slow
  - 🔴 This is unstable: #409 has multiple reports of people having a broken Docker image, which is a mess

- `docker run --rm -it -v $(PWD):/var/task:ro,delegated bref/php-74 my-hello-function.php '{}'`
  - 👍 Runs in Docker (mirrors the prod environment)
  - 👍 Native Docker command which gives more control than `serverless invoke local`
  - 🔴 Command is long and hard to remember
  - 🔴 Requires to pass the handler file name instead of the function name
  - 🔴 An even more complex command is required to forward AWS credentials and other variables like profile & region

## The solution

This PR introduces a new command:

```bash
$ vendor/bin/bref local hello
START RequestId: 8f507cfc-example-4697-b07a-ac58fc914c95 Version: $LATEST
This is a log line
END RequestId: 8f507cfc-example-4697-b07a-ac58fc914c95
REPORT RequestId: 8f507cfc-example-4697-b07a-ac58fc914c95 Duration: 3 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 4 MB

"Hello world"
```

Output example:

image

- 👍 The command is simple
- 👍 It uses the same names as in `serverless.yml`
- It runs **without Docker**, using your installed PHP CLI:
  - 👍 It's as fast as possible
  - 👍 AWS credentials & environment variables work as usual
- It can also run **inside Docker** for those who want: `docker run --rm -it -v $(PWD):/var/task:ro,delegated bref/php-74 vendor/bin/bref local hello`
  - 👍 Runs in Docker (mirrors the prod environment)

That way, users can get the best of both worlds!

It is also possible to pass event data as JSON:

```bash
$ vendor/bin/bref local hello '{"name":"Matthieu"}'
START RequestId: 8f507cfc-example-4697-b07a-ac58fc914c95 Version: $LATEST
This is a log line
END RequestId: 8f507cfc-example-4697-b07a-ac58fc914c95
REPORT RequestId: 8f507cfc-example-4697-b07a-ac58fc914c95 Duration: 3 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 4 MB

"Hello Matthieu"
```

If you do not use `serverless.yml` but something else like SAM/CDK/CloudFormation/Terraform, use the `--handler` parameter instead:

```bash
$ vendor/bin/bref local --handler=my-function.php
Hello world

# With JSON event data
$ vendor/bin/bref local '{"name": "Jane"}' --handler=my-function.php
Hello Jane

# With JSON in a file
$ vendor/bin/bref local --handler=my-function.php --file=event.json
Hello Jane
```

## TODO

- [x] More robust code
- [x] Allow to pass event data from a file
- [x] Documentation
- [x] Support SAM/CDK/Terraform/etc.

### CODE REVIEW

**Comment by tristanbes** [comment]
a solution without docker yaaay ! :D 

We'll try to test it in the upcoming weeks, thank you @mnapoli

File: src/Console/Command/Local.php [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+            $event = $data ? json_decode($data, true, 512, JSON_THROW_ON_ERROR) : null;
+        } catch (JsonException $e) {
+            throw new Exception('The JSON provided for the event data is invalid JSON.');
+        }
+
+        // Same configuration as the Bref runtime on Lambda
+        ini_set('display_errors', '1');
+        error_reporting(E_ALL);
+
+        $requestId = '8f507cfc-example-4697-b07a-ac58fc914c95';
```
Comment (Orkin) [inline src/Console/Command/Local.php:62]: It is normal to get the request id here hardcoded ?

Comment (mnapoli) [reply src/Console/Command/Local.php:62]: Yes I wanted to provide one that looks like a real ID, but I thought why generate a random one… I think as a first version that will do well, if anyone actually uses those IDs for something they can always improve that by sending a PR that generates random ones?

File: src/Console/Command/Local.php [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+        $this->logEnd($startTime, $io, $requestId);
+        // Show the invocation result
+        $io->block(json_encode($result, JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT), null, 'fg=black;bg=green', '', true);
+
+        return 0;
+    }
+
+    private function handlerFromServerlessYml(string $function): string
+    {
+        if (! file_exists('serverless.yml')) {
```
Comment (Fabex) [inline src/Console/Command/Local.php:82]: Do you think is it possible to set the path where is the serverless.yml as a option of the command? For some reasons our serverless.yml is not in the root folder but in a subfolder and if we can not set the folder we should copy the serverless file in the root folder that is not cool for us.

Comment (mnapoli) [reply src/Console/Command/Local.php:82]: Sure that makes sense, we can mirror the `--config` option of `serverless` (`bref local --config=foo/serverless.yml ...`), feel free to send a PR on branch `v1.0`.
